name: Build Docker Image (amd64 & arm64)
on:
  schedule:
    - cron: '00 19 * * 6'
  workflow_dispatch:
  
jobs:
  ImageBuild:
    name: Build Keycloak Custom Docker Image (amd64 & arm64)
    runs-on: ubuntu-latest
    steps:
      - name: Slack notification of build start
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_USERNAME: GitHub Actions
          SLACK_COLOR: "#4381de"
          SLACK_ICON: "https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png"
          SLACK_TITLE: Start keycloak image build 
          SLACK_MESSAGE: |
            Run number : #${{ github.run_number }}
          
      - name: Check out
        uses: actions/checkout@v3

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ github.ref }}-${{ github.sha }}
          restore-keys: |
            ${{ github.ref }}-${{ github.sha }}
            ${{ github.ref }}
            refs/head/main

      # ghcrにログイン
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: walnuts1018
          password: ${{ secrets.GITHUB_TOKEN }}

      # buildxを設定
      - name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v3
        with:
          buildx-version: latest
          qemu-version: latest

      # Docker Imageをビルド
      - name: Build and push Docker images
        uses: docker/build-push-action@v4.0.0
        with:
          push: true
          context: .
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/walnuts1018/keycloak:latest
            ghcr.io/walnuts1018/keycloak:${{ github.sha }}-${{ github.run_number }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache            
          
  SucceessNotification:
    if: ${{ success() }}
    name: Send Success Message
    needs: [ImageBuild]
    runs-on: ubuntu-latest
    steps:
      - name: Send Message to Slack
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_USERNAME: GitHub Actions
          SLACK_ICON: "https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png"
          SLACK_TITLE: Keycloak id:mage build succeeded
          SLACK_MESSAGE: |
            Run number : #${{ github.run_number }}
            Image tag : ${{ github.sha }}-${{ github.run_number }}
            Image URL : 
           
  FailureAlert:
    if: ${{ failure() }}
    name: Notify failure
    needs: [ImageBuild]
    runs-on: ubuntu-latest
    steps:
      - name: Send Failure Alert to Slack
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_USERNAME: GitHub Actions
          SLACK_ICON: "https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png"
          SLACK_TITLE: Keycloak image build failed
          SLACK_COLOR: danger
          SLACK_MESSAGE: 'Run number : #${{ github.run_number }}'
